version: "3"

services:
  uf-api:
    build: .
    restart: unless-stopped
    image: uf-api-img
    container_name: uf-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./:/code
    ports:
      - "8000:80"
    deploy:
      resources:
        limits:
          memory: 3250M
        reservations:
          memory: 500M